version: '2'
services:
  schmooze:
    image: outstand/schmooze:latest
    network_mode: host
    cap_add:
      - NET_ADMIN
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - .:/srv
