source 'https://rubygems.org'

gem 'thor', '~> 0.20'
gem 'excon', '~> 0.60.0'
gem 'docker-api', '~> 1.34'
gem 'concurrent-ruby', '~> 1.0'
gem 'concurrent-ruby-edge', '~> 0.3'
gem 'metaractor', '~> 0.5'
gem 'tty-command'
gem 'multi_json'
